[package]
name = "text_circle_validator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.5"
wasm-bindgen = "0.2.83"

[lib]
crate-type = ["cdylib"]

[profile.dev]
opt-level = "s"

